# 資料庫連線設定
spring.datasource.url=jdbc:mysql://localhost:3306/gjun_sit
spring.datasource.username=root
spring.datasource.password=1234

# 根據 Entity 自動更新資料庫結構
spring.jpa.hibernate.ddl-auto=update

# 顯示產生的 SQL 
spring.jpa.show-sql=true

# 服務埠號
server.port=8080

# 伺服器基礎設定
server.address=0.0.0.0

# 開啟Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JWT
jwt.secret=ECS_SIT_Development_Secret_Key_2026_v1

# 綠界測試環境金鑰
ecpay.merchant-id=2000132
ecpay.hash-key=5294y06JbCwM5u5f
ecpay.hash-iv=v77hoKGq4kWxJtE1

# 這是綠界通知你後端的網址 (sit 環境可能用 ngrok 網址)
ecpay.return-url=https://palladous-upmost-margaretta.ngrok-free.dev/api/payment/callback
# 使用者付款完要跳轉回前端的網址
ecpay.client-back-url=http://localhost:5173/checkout/success

# 讓 Log 顯示 SQL 的參數內容
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE