# 應用程式名稱
spring.application.name=ECS

# 資料庫驅動 (所有環境都用 MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 基礎設定
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger 預設路徑
springdoc.swagger-ui.path=/swagger-ui.html

# 伺服器基礎設定
server.address=0.0.0.0

# 預設啟動的 Profile (建議開發時設為 sit)
spring.profiles.active=sit

# 處理檔案上傳大小限制
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# 設定 JSON 回傳的時間格式 (避免前端拿到一串數字時間)
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

jwt.secret=8c9b55dd8bca22cd53a71d9bb5f607da
# 一般登入設為 24 小時 
jwt.normal-expiration=10000
# 保持登入設為 7 天
jwt.remember-me-expiration=604800000

# jwt.secret=8c9b55dd8bca22cd53a71d9bb5f607da

# 日誌路徑
# logging.file.name=logs/ecs.log
