# 資料庫連線設定
spring.datasource.url=jdbc:mysql://localhost:3306/gjun_sit
spring.datasource.username=root
spring.datasource.password=1234

#自動更新資料庫結構
spring.jpa.hibernate.ddl-auto=update

# 服務埠號
server.port=8080

# 伺服器基礎設定
server.address=0.0.0.0

# 開啟Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JWT
jwt.secret=ECS_SIT_Development_Secret_Key_2026_v1