# 資料庫連線設定
spring.datasource.url=jdbc:mysql://[正式機公網IP]:3306/gjun_prod
spring.datasource.username=prod_admin
spring.datasource.password=StrongPassword123

# 正式環境設定 none 
spring.jpa.hibernate.ddl-auto=none

# 正式環境埠號
server.port=8080

# 關閉 Swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# JWT
jwt.secret=f2d9a3b8c7e1d4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f