name: ECS Shop CI

on:
  push:
    branches: ["dev_Lucas"] # 平常開發分支 push 時，立刻做檢查
  pull_request:
    branches: ["main"] # Merge時，自動觸發檢查

jobs:
  build:
    # 使用 GitHub 提供的最新版 Ubuntu 虛擬機
    runs-on:
      ubuntu-latest

      # 在雲端機器啟動一個臨時的 MySQL
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: ecs_sit
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # 複製 Git 程式碼到虛擬機中
      - name: Checkout code
        uses: actions/checkout@v4

      # 安裝 Java 環境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven # 啟用快取，下次跑 CI 時會變快

      # 執行 Maven 編譯與測試
      - name: Build with Maven

        # 從 GitHub 內建環境變數讀取真實變數
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          GOOGLE_CLOUD_API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: mvn clean package

        # =================  Docker =================

        # 登入到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 設定 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 執行 Docker 打包並推送
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ecs-backend:${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && format('{0}/ecs-backend:latest', secrets.DOCKERHUB_USERNAME) || format('{0}/ecs-backend:dev', secrets.DOCKERHUB_USERNAME) }}
